// drive_in~init1.c
// AutoMod 12.6.1 Generated File
// Build: 12.6.1.12
// Model name:	drive_in
// Model path:	C:\Users\Periot\Desktop\Digital production project\Quick Fix Demon - project delivery - Digital production mod. 1\Automod project\drive_in.dir\
// Generated:	Sun Jun 26 14:24:14 2022
// Applied/AutoMod Licensee Confidential
// NO DISTRIBUTION OR REPRODUCTION RIGHTS GRANTED!
// Copyright (c) 1988-2015 Applied Materials All rights reserved.
//
// All Rights Reserved.  Reproduction or transmission in whole or
// in part, in any form or by any means, electronic, mechanical or
// otherwise, is prohibited without the prior written consent of
// copyright owner.
//
// Licensed Material - Property of Applied Materials, Inc.
//
// Applied Materials, Inc.
// 3050 Bowers Drive
// P.O. Box 58039
// Santa Clara, CA 95054-3299
// U.S.A.
//


#include "decls.h"

void
initglobs0()
{
	am_model.$sys = model;
	am_model.am_conv.$sys = symGetSystemDataByName(am_model.$sys, "conv");
	am_model.am_conv.am_sta_first_ing_1 = symGetSystemDataByName(am_model.am_conv.$sys, "sta_first_ing_1");
	am_model.am_conv.am_sta_first_ing_2 = symGetSystemDataByName(am_model.am_conv.$sys, "sta_first_ing_2");
	am_model.am_conv.am_sta_first_ing_3 = symGetSystemDataByName(am_model.am_conv.$sys, "sta_first_ing_3");
	am_model.am_conv.am_sta_room = symGetSystemDataByName(am_model.am_conv.$sys, "sta_room");
	am_model.am_conv.am_sta_second_ing_3 = symGetSystemDataByName(am_model.am_conv.$sys, "sta_second_ing_3");
	am_model.am_conv.am_sta_second_ing_1 = symGetSystemDataByName(am_model.am_conv.$sys, "sta_second_ing_1");
	am_model.am_conv.am_sta_car = symGetSystemDataByName(am_model.am_conv.$sys, "sta_car");
	am_model.am_conv.am_sta_second_ing_2 = symGetSystemDataByName(am_model.am_conv.$sys, "sta_second_ing_2");
	am_model.am_conv.am_parentsys = symGetSystemDataByName(am_model.am_conv.$sys, "parentsys");
	am_model.am_conv.am_sta_drink = symGetSystemDataByName(am_model.am_conv.$sys, "sta_drink");
	am_model.am_conv.am_sta_chips = symGetSystemDataByName(am_model.am_conv.$sys, "sta_chips");
	am_model.am_conv.am_sta_bread = symGetSystemDataByName(am_model.am_conv.$sys, "sta_bread");
	am_model.am_conv_car.$sys = symGetSystemDataByName(am_model.$sys, "conv_car");
	am_model.am_conv_car.am_sta_order = symGetSystemDataByName(am_model.am_conv_car.$sys, "sta_order");
	am_model.am_conv_car.am_sta_start = symGetSystemDataByName(am_model.am_conv_car.$sys, "sta_start");
	am_model.am_conv_car.am_parentsys = symGetSystemDataByName(am_model.am_conv_car.$sys, "parentsys");
	am_model.am_conv_car.am_sta_pay = symGetSystemDataByName(am_model.am_conv_car.$sys, "sta_pay");
	am_model.am_conv_car.am_sta_take = symGetSystemDataByName(am_model.am_conv_car.$sys, "sta_take");
	am_model.am_conv_person.$sys = symGetSystemDataByName(am_model.$sys, "conv_person");
	am_model.am_conv_person.am_person_out = symGetSystemDataByName(am_model.am_conv_person.$sys, "person_out");
	am_model.am_conv_person.am_parentsys = symGetSystemDataByName(am_model.am_conv_person.$sys, "parentsys");
	am_model.am_conv_person.am_person_in = symGetSystemDataByName(am_model.am_conv_person.$sys, "person_in");
	am_model.am_restock.$sys = symGetSystemDataByName(am_model.$sys, "restock");
	am_model.am_restock.am_re_drink = symGetSystemDataByName(am_model.am_restock.$sys, "re_drink");
	am_model.am_restock.am_re_chips = symGetSystemDataByName(am_model.am_restock.$sys, "re_chips");
	am_model.am_restock.am_re_veg = symGetSystemDataByName(am_model.am_restock.$sys, "re_veg");
	am_model.am_restock.am_re_stocker = symGetSystemDataByName(am_model.am_restock.$sys, "re_stocker");
	am_model.am_restock.am_re_meat_1 = symGetSystemDataByName(am_model.am_restock.$sys, "re_meat_1");
	am_model.am_restock.am_re_stock = symGetSystemDataByName(am_model.am_restock.$sys, "re_stock");
	am_model.am_restock.am_re_chick_1 = symGetSystemDataByName(am_model.am_restock.$sys, "re_chick_1");
	am_model.am_restock.am_re_chick_2 = symGetSystemDataByName(am_model.am_restock.$sys, "re_chick_2");
	am_model.am_restock.am_re_meat_2 = symGetSystemDataByName(am_model.am_restock.$sys, "re_meat_2");
	am_model.am_restock.am_parentsys = symGetSystemDataByName(am_model.am_restock.$sys, "parentsys");
	am_model.am_restock.am_restocker_seg = symGetSystemDataByName(am_model.am_restock.$sys, "restocker_seg");
	am_model.am_restock.am_re_bread = symGetSystemDataByName(am_model.am_restock.$sys, "re_bread");
	am_model.am_waiter.$sys = symGetSystemDataByName(am_model.$sys, "waiter");
	am_model.am_waiter.am_w_room_in = symGetSystemDataByName(am_model.am_waiter.$sys, "w_room_in");
	am_model.am_waiter.am_w_room_out = symGetSystemDataByName(am_model.am_waiter.$sys, "w_room_out");
	am_model.am_waiter.am_parentsys = symGetSystemDataByName(am_model.am_waiter.$sys, "parentsys");
	am_model.am_waiter.am_waiter_segment = symGetSystemDataByName(am_model.am_waiter.$sys, "waiter_segment");
	am_model.am_waiter.am_waiter = symGetSystemDataByName(am_model.am_waiter.$sys, "waiter");
	am_model.am_V_car_out_counter$var = symGetSystemDataByName(am_model.$sys, "V_car_out_counter");
	am_model.am_V_car_out_counter$var->data = (void*)&am_model.am_V_car_out_counter;
	am_model.am_L_menu = symGetSystemDataByName(am_model.$sys, "L_menu");
	am_model.am_LB_stock = symGetSystemDataByName(am_model.$sys, "LB_stock");
	am_model.am_V_file_car_w_t_ptr$var = symGetSystemDataByName(am_model.$sys, "V_file_car_w_t_ptr");
	am_model.am_V_file_car_w_t_ptr$var->data = (void*)&am_model.am_V_file_car_w_t_ptr;
	am_model.am_V_file_input_ptr$var = symGetSystemDataByName(am_model.$sys, "V_file_input_ptr");
	am_model.am_V_file_input_ptr$var->data = (void*)&am_model.am_V_file_input_ptr;
	am_model.am_die = symGetSystemDataByName(am_model.$sys, "die");
	am_model.am_V_stock_type$att = symGetSystemDataByName(am_model.$sys, "V_stock_type");
	am_model.am_L_veggy_complete = symGetSystemDataByName(am_model.$sys, "L_veggy_complete");
	am_model.am_V_file_downtime_ptr$var = symGetSystemDataByName(am_model.$sys, "V_file_downtime_ptr");
	am_model.am_V_file_downtime_ptr$var->data = (void*)&am_model.am_V_file_downtime_ptr;
	am_model.am_V_order_level$att = symGetSystemDataByName(am_model.$sys, "V_order_level");
	am_model.am_P_menu = symGetSystemDataByName(am_model.$sys, "P_menu");
	am_model.am_L_veggy_ing_1 = symGetSystemDataByName(am_model.$sys, "L_veggy_ing_1");
	am_model.am_V_arrival_time$att = symGetSystemDataByName(am_model.$sys, "V_arrival_time");
	am_model.am_V_pers_queue_w_time$var = symGetSystemDataByName(am_model.$sys, "V_pers_queue_w_time");
	am_model.am_V_pers_queue_w_time$var->data = (void*)&am_model.am_V_pers_queue_w_time;
	am_model.am_V_headers$var = symGetSystemDataByName(am_model.$sys, "V_headers");
	am_model.am_V_headers$var->data = (void*)&am_model.am_V_headers;
	am_model.am_V_chips$att = symGetSystemDataByName(am_model.$sys, "V_chips");
	am_model.am_L_veggy_closed = symGetSystemDataByName(am_model.$sys, "L_veggy_closed");
	am_model.am_L_bread = symGetSystemDataByName(am_model.$sys, "L_bread");
	am_model.am_stream_R_op_drink_1 = symGetSystemDataByName(am_model.$sys, "stream_R_op_drink_1");
	am_model.am_V_load_ptr$att = symGetSystemDataByName(am_model.$sys, "V_load_ptr");
	am_model.am_V_stock_downtime$var = symGetSystemDataByName(am_model.$sys, "V_stock_downtime");
	am_model.am_V_stock_downtime$var->data = (void*)&am_model.am_V_stock_downtime;
	am_model.am_V_car_queue_w_time$var = symGetSystemDataByName(am_model.$sys, "V_car_queue_w_time");
	am_model.am_V_car_queue_w_time$var->data = (void*)&am_model.am_V_car_queue_w_time;
	am_model.am_V_eat_avg$var = symGetSystemDataByName(am_model.$sys, "V_eat_avg");
	am_model.am_V_eat_avg$var->data = (void*)&am_model.am_V_eat_avg;
	am_model.am_L_chicken_complete = symGetSystemDataByName(am_model.$sys, "L_chicken_complete");
	am_model.am_V_drink$att = symGetSystemDataByName(am_model.$sys, "V_drink");
	am_model.am_V_order_provenience$att = symGetSystemDataByName(am_model.$sys, "V_order_provenience");
	am_model.am_OL_take_person = symGetSystemDataByName(am_model.$sys, "OL_take_person");
	am_model.am_stream_R_op_second_1 = symGetSystemDataByName(am_model.$sys, "stream_R_op_second_1");
	am_model.am_V_file_menu_list_name$var = symGetSystemDataByName(am_model.$sys, "V_file_menu_list_name");
	am_model.am_V_file_menu_list_name$var->data = (void*)&am_model.am_V_file_menu_list_name;
	am_model.am_stream_R_op_take_car_1 = symGetSystemDataByName(am_model.$sys, "stream_R_op_take_car_1");
	am_model.am_OPCTimestamp$var = symGetSystemDataByName(am_model.$sys, "OPCTimestamp");
	am_model.am_OPCTimestamp$var->data = (void*)&am_model.am_OPCTimestamp;
	am_model.am_Q_room = symGetSystemDataByName(am_model.$sys, "Q_room");
	am_model.am_V_pers_room_counter$var = symGetSystemDataByName(am_model.$sys, "V_pers_room_counter");
	am_model.am_V_pers_room_counter$var->data = (void*)&am_model.am_V_pers_room_counter;
	am_model.am_V_pers_eating_counter$var = symGetSystemDataByName(am_model.$sys, "V_pers_eating_counter");
	am_model.am_V_pers_eating_counter$var->data = (void*)&am_model.am_V_pers_eating_counter;
	am_model.am_OL_take_car = symGetSystemDataByName(am_model.$sys, "OL_take_car");
	am_model.am_R_op_bread = symGetSystemDataByName(am_model.$sys, "R_op_bread");
	am_model.am_T_sta_proc_time_ratio = symGetSystemDataByName(am_model.$sys, "T_sta_proc_time_ratio");
	am_model.am_V_order_ready$att = symGetSystemDataByName(am_model.$sys, "V_order_ready");
	am_model.am_V_file_menu_list_ptr$var = symGetSystemDataByName(am_model.$sys, "V_file_menu_list_ptr");
	am_model.am_V_file_menu_list_ptr$var->data = (void*)&am_model.am_V_file_menu_list_ptr;
	am_model.am_V_pers_current_counter$var = symGetSystemDataByName(am_model.$sys, "V_pers_current_counter");
	am_model.am_V_pers_current_counter$var->data = (void*)&am_model.am_V_pers_current_counter;
	am_model.am_V_sta_proc_time_ratio$var = symGetSystemDataByName(am_model.$sys, "V_sta_proc_time_ratio");
	am_model.am_V_sta_proc_time_ratio = (double*)xcalloc(10, sizeof(*am_model.am_V_sta_proc_time_ratio));
	am_model.am_V_sta_proc_time_ratio$var->data = (void*)am_model.am_V_sta_proc_time_ratio;
	am_model.am_V_pers_counter$var = symGetSystemDataByName(am_model.$sys, "V_pers_counter");
	am_model.am_V_pers_counter$var->data = (void*)&am_model.am_V_pers_counter;
	am_model.am_R_op_second = symGetSystemDataByName(am_model.$sys, "R_op_second");
	am_model.am_Q_restock = symGetSystemDataByName(am_model.$sys, "Q_restock");
	am_model.am_V_load_type_ptrs$att = symGetSystemDataByName(am_model.$sys, "V_load_type_ptrs");
	am_model.am_V_pers_out_counter$var = symGetSystemDataByName(am_model.$sys, "V_pers_out_counter");
	am_model.am_V_pers_out_counter$var->data = (void*)&am_model.am_V_pers_out_counter;
	am_model.am_V_car_current_counter$var = symGetSystemDataByName(am_model.$sys, "V_car_current_counter");
	am_model.am_V_car_current_counter$var->data = (void*)&am_model.am_V_car_current_counter;
	am_model.am_V_menu_pointer$att = symGetSystemDataByName(am_model.$sys, "V_menu_pointer");
	am_model.am_L_meat_ing_1 = symGetSystemDataByName(am_model.$sys, "L_meat_ing_1");
	am_model.am_V_menu_counter$var = symGetSystemDataByName(am_model.$sys, "V_menu_counter");
	am_model.am_V_menu_counter$var->data = (void*)&am_model.am_V_menu_counter;
	am_model.am_P_stock = symGetSystemDataByName(am_model.$sys, "P_stock");
	am_model.am_L_veggy_drink = symGetSystemDataByName(am_model.$sys, "L_veggy_drink");
	am_model.am_V_stock_location$att = symGetSystemDataByName(am_model.$sys, "V_stock_location");
	am_model.am_Q_take_person = symGetSystemDataByName(am_model.$sys, "Q_take_person");
	am_model.am_stream_R_op_first_1 = symGetSystemDataByName(am_model.$sys, "stream_R_op_first_1");
	am_model.am_L_stock = symGetSystemDataByName(am_model.$sys, "L_stock");
	am_model.am_modelsys = symGetSystemDataByName(am_model.$sys, "modelsys");
	am_model.am_V_station_proc_time$att = symGetSystemDataByName(am_model.$sys, "V_station_proc_time");
	am_model.am_V_file_pers_w_t_name$var = symGetSystemDataByName(am_model.$sys, "V_file_pers_w_t_name");
	am_model.am_V_file_pers_w_t_name$var->data = (void*)&am_model.am_V_file_pers_w_t_name;
	am_model.am_L_chicken_closed = symGetSystemDataByName(am_model.$sys, "L_chicken_closed");
	am_model.am_C_stock = symGetSystemDataByName(am_model.$sys, "C_stock");
	am_model.am_V_order_id$att = symGetSystemDataByName(am_model.$sys, "V_order_id");
	am_model.am_Q_totem = symGetSystemDataByName(am_model.$sys, "Q_totem");
	am_model.am_Q_person = symGetSystemDataByName(am_model.$sys, "Q_person");
	am_model.am_P_person = symGetSystemDataByName(am_model.$sys, "P_person");
	am_model.am_L_chicken_ing_1 = symGetSystemDataByName(am_model.$sys, "L_chicken_ing_1");
	am_model.am_L_meat_chips = symGetSystemDataByName(am_model.$sys, "L_meat_chips");
	am_model.am_R_op_first = symGetSystemDataByName(am_model.$sys, "R_op_first");
	am_model.am_R_op_drink = symGetSystemDataByName(am_model.$sys, "R_op_drink");
	am_model.am_V_file_downtime_name$var = symGetSystemDataByName(am_model.$sys, "V_file_downtime_name");
	am_model.am_V_file_downtime_name$var->data = (void*)&am_model.am_V_file_downtime_name;
	am_model.am_LB_eating_pers = symGetSystemDataByName(am_model.$sys, "LB_eating_pers");
	am_model.am_Q_take_car = symGetSystemDataByName(am_model.$sys, "Q_take_car");
	am_model.am_L_chicken_chips = symGetSystemDataByName(am_model.$sys, "L_chicken_chips");
	am_model.am_V_menu_processing_time$att = symGetSystemDataByName(am_model.$sys, "V_menu_processing_time");
	am_model.am_P_init_output = symGetSystemDataByName(am_model.$sys, "P_init_output");
	am_model.am_L_meat_complete = symGetSystemDataByName(am_model.$sys, "L_meat_complete");
	am_model.am_L_person = symGetSystemDataByName(am_model.$sys, "L_person");
	am_model.am_P_init_stock = symGetSystemDataByName(am_model.$sys, "P_init_stock");
	am_model.am_L_veggy_chips = symGetSystemDataByName(am_model.$sys, "L_veggy_chips");
	am_model.am_L_meat_closed = symGetSystemDataByName(am_model.$sys, "L_meat_closed");
	am_model.am_stream_L_dummy_1 = symGetSystemDataByName(am_model.$sys, "stream_L_dummy_1");
	am_model.am_L_meat_drink = symGetSystemDataByName(am_model.$sys, "L_meat_drink");
	am_model.am_stream_R_op_pay_1 = symGetSystemDataByName(am_model.$sys, "stream_R_op_pay_1");
	am_model.am_V_menu_pers_time$var = symGetSystemDataByName(am_model.$sys, "V_menu_pers_time");
	am_model.am_V_menu_pers_time$var->data = (void*)&am_model.am_V_menu_pers_time;
	am_model.am_stream0 = symGetSystemDataByName(am_model.$sys, "stream0");
	am_model.am_P_init_read_input = symGetSystemDataByName(am_model.$sys, "P_init_read_input");
	am_model.am_stream_R_op_chips_1 = symGetSystemDataByName(am_model.$sys, "stream_R_op_chips_1");
	am_model.am_V_debug$var = symGetSystemDataByName(am_model.$sys, "V_debug");
	am_model.am_V_debug$var->data = (void*)&am_model.am_V_debug;
	am_model.am_R_op_chips = symGetSystemDataByName(am_model.$sys, "R_op_chips");
	am_model.am_L_order_room = symGetSystemDataByName(am_model.$sys, "L_order_room");
	am_model.am_P_init = symGetSystemDataByName(am_model.$sys, "P_init");
	am_model.am_P_menu_generator = symGetSystemDataByName(am_model.$sys, "P_menu_generator");
	am_model.am_V_file_input_name$var = symGetSystemDataByName(am_model.$sys, "V_file_input_name");
	am_model.am_V_file_input_name$var->data = (void*)&am_model.am_V_file_input_name;
	am_model.am_L_car = symGetSystemDataByName(am_model.$sys, "L_car");
	am_model.am_L_chicken_drink = symGetSystemDataByName(am_model.$sys, "L_chicken_drink");
	am_model.am_V_sing_order_car_avg$var = symGetSystemDataByName(am_model.$sys, "V_sing_order_car_avg");
	am_model.am_V_sing_order_car_avg$var->data = (void*)&am_model.am_V_sing_order_car_avg;
	am_model.am_V_sta_oper_time_avg$var = symGetSystemDataByName(am_model.$sys, "V_sta_oper_time_avg");
	am_model.am_V_sta_oper_time_avg = (ASITime*)xcalloc(10, sizeof(*am_model.am_V_sta_oper_time_avg));
	am_model.am_V_sta_oper_time_avg$var->data = (void*)am_model.am_V_sta_oper_time_avg;
	am_model.am_P_car = symGetSystemDataByName(am_model.$sys, "P_car");
	am_model.am_V_order_counter$var = symGetSystemDataByName(am_model.$sys, "V_order_counter");
	am_model.am_V_order_counter$var->data = (void*)&am_model.am_V_order_counter;
	am_model.am_P_order_room = symGetSystemDataByName(am_model.$sys, "P_order_room");
	am_model.am_V_order_time$att = symGetSystemDataByName(am_model.$sys, "V_order_time");
	am_model.am_V_menu_car_time$var = symGetSystemDataByName(am_model.$sys, "V_menu_car_time");
	am_model.am_V_menu_car_time$var->data = (void*)&am_model.am_V_menu_car_time;
	am_model.am_V_file_car_w_t_name$var = symGetSystemDataByName(am_model.$sys, "V_file_car_w_t_name");
	am_model.am_V_file_car_w_t_name$var->data = (void*)&am_model.am_V_file_car_w_t_name;
	am_model.am_V_menu_value$att = symGetSystemDataByName(am_model.$sys, "V_menu_value");
	am_model.am_R_op_take_car = symGetSystemDataByName(am_model.$sys, "R_op_take_car");
	am_model.am_R_op_pay = symGetSystemDataByName(am_model.$sys, "R_op_pay");
	am_model.am_V_file_pers_w_t_ptr$var = symGetSystemDataByName(am_model.$sys, "V_file_pers_w_t_ptr");
	am_model.am_V_file_pers_w_t_ptr$var->data = (void*)&am_model.am_V_file_pers_w_t_ptr;
	am_model.am_stream_R_op_bread_1 = symGetSystemDataByName(am_model.$sys, "stream_R_op_bread_1");
	am_model.am_OPCQuality$var = symGetSystemDataByName(am_model.$sys, "OPCQuality");
	am_model.am_OPCQuality$var->data = (void*)&am_model.am_OPCQuality;
	am_model.am_V_menu_type$att = symGetSystemDataByName(am_model.$sys, "V_menu_type");
	am_model.am_V_sing_order_pers_avg$var = symGetSystemDataByName(am_model.$sys, "V_sing_order_pers_avg");
	am_model.am_V_sing_order_pers_avg$var->data = (void*)&am_model.am_V_sing_order_pers_avg;
	am_model.am_OL_waiting_person = symGetSystemDataByName(am_model.$sys, "OL_waiting_person");
	am_model.am_LB_waiting_pers = symGetSystemDataByName(am_model.$sys, "LB_waiting_pers");
	am_model.am_V_order_dim$att = symGetSystemDataByName(am_model.$sys, "V_order_dim");
	model_P_init_read_inputa_init(&am_model);
	model_P_persona_init(&am_model);
	model_P_cara_init(&am_model);
	model_P_menua_init(&am_model);
	model_P_menu_generatora_init(&am_model);
	model_P_order_rooma_init(&am_model);
	model_P_init_stocka_init(&am_model);
	model_P_stocka_init(&am_model);
	model_P_inita_init(&am_model);
	model_P_menul_init(&am_model);
	model_P_init_outputa_init(&am_model);
	{
		Iter(List, FileList) it = Begin(List, FileList, &((ProcSystem*)am_model.$sys)->files);

	}
	{
		Iter(List, AMTypeList) it = Begin(List, AMTypeList, &((ProcSystem*)am_model.$sys)->types);

		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(Acceleration);
		IterValue(List, AMTypeList, it)->valstrfunc = Acceleration_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc = str2String;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(block*);
		IterValue(List, AMTypeList, it)->valstrfunc = BlockPtr_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))BlockPtr_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(AMBlockList*);
		IterValue(List, AMTypeList, it)->valstrfunc = BlockList_valstrfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(ASI_Color);
		IterValue(List, AMTypeList, it)->valstrfunc = Color_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))Color_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(Container*);
		IterValue(List, AMTypeList, it)->valstrfunc = ContainerPtr_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))ContainerPtr_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(AMContainerList*);
		IterValue(List, AMTypeList, it)->valstrfunc = ContainerList_valstrfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(counter*);
		IterValue(List, AMTypeList, it)->valstrfunc = CounterPtr_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))CounterPtr_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(Distance);
		IterValue(List, AMTypeList, it)->valstrfunc = Distance_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc = str2String;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(iofile*);
		IterValue(List, AMTypeList, it)->valstrfunc = FilePtr_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))FilePtr_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(bgraph*);
		IterValue(List, AMTypeList, it)->valstrfunc = GraphPtr_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))GraphPtr_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(int32);
		IterValue(List, AMTypeList, it)->valstrfunc = Integer_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc = str2String;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(label*);
		IterValue(List, AMTypeList, it)->valstrfunc = LabelPtr_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))LabelPtr_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(load*);
		IterValue(List, AMTypeList, it)->valstrfunc = LoadPtr_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))LoadPtr_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(AMLoadList*);
		IterValue(List, AMTypeList, it)->valstrfunc = LoadList_valstrfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(loadtype*);
		IterValue(List, AMTypeList, it)->valstrfunc = LoadTypePtr_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))LoadTypePtr_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(simloc*);
		IterValue(List, AMTypeList, it)->valstrfunc = Location_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))Location_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(AMLocationList*);
		IterValue(List, AMTypeList, it)->valstrfunc = LocationList_valstrfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(LocationType*);
		IterValue(List, AMTypeList, it)->valstrfunc = LocationTypePtr_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))LocationTypePtr_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(AMLocationTypeList*);
		IterValue(List, AMTypeList, it)->valstrfunc = LocationTypeList_valstrfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(State_machine*);
		IterValue(List, AMTypeList, it)->valstrfunc = MonitorPtr_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))MonitorPtr_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterInc(List, AMTypeList, it);
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(ConvMotor*);
		IterValue(List, AMTypeList, it)->valstrfunc = MotorPtr_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))MotorPtr_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(AMConvMotorList*);
		IterValue(List, AMTypeList, it)->valstrfunc = MotorList_valstrfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(MotorType*);
		IterValue(List, AMTypeList, it)->valstrfunc = MotorTypePtr_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))MotorTypePtr_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(AMMotorTypeList*);
		IterValue(List, AMTypeList, it)->valstrfunc = MotorTypeList_valstrfunc;
		IterInc(List, AMTypeList, it);
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(ordlist*);
		IterValue(List, AMTypeList, it)->valstrfunc = OrderListPtr_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))OrderListPtr_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(Path*);
		IterValue(List, AMTypeList, it)->valstrfunc = PathPtr_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))PathPtr_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(AMPathList*);
		IterValue(List, AMTypeList, it)->valstrfunc = PathList_valstrfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(AgvPathType*);
		IterValue(List, AMTypeList, it)->valstrfunc = PathTypePtr_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))PathTypePtr_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(AMAgvPathTypeList*);
		IterValue(List, AMTypeList, it)->valstrfunc = PathTypeList_valstrfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(Photoeye*);
		IterValue(List, AMTypeList, it)->valstrfunc = PhotoeyePtr_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))PhotoeyePtr_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(AMPhotoList*);
		IterValue(List, AMTypeList, it)->valstrfunc = PhotoeyeList_valstrfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(PhotoeyeType*);
		IterValue(List, AMTypeList, it)->valstrfunc = PhotoeyeTypePtr_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))PhotoeyeTypePtr_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(AMPhotoeyeTypeList*);
		IterValue(List, AMTypeList, it)->valstrfunc = PhotoeyeTypeList_valstrfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(process*);
		IterValue(List, AMTypeList, it)->valstrfunc = ProcessPtr_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))ProcessPtr_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(queue*);
		IterValue(List, AMTypeList, it)->valstrfunc = QueuePtr_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))QueuePtr_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(AMQueueList*);
		IterValue(List, AMTypeList, it)->valstrfunc = QueueList_valstrfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(Rate);
		IterValue(List, AMTypeList, it)->valstrfunc = Rate_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc = str2String;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(double);
		IterValue(List, AMTypeList, it)->valstrfunc = Real_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc = str2String;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(resource*);
		IterValue(List, AMTypeList, it)->valstrfunc = ResourcePtr_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))ResourcePtr_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(AMResourceList*);
		IterValue(List, AMTypeList, it)->valstrfunc = ResourceList_valstrfunc;
		IterInc(List, AMTypeList, it);
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(SchedJob*);
		IterValue(List, AMTypeList, it)->valstrfunc = SchedJobPtr_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))SchedJobPtr_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(AMSchedJobList*);
		IterValue(List, AMTypeList, it)->valstrfunc = SchedJobList_valstrfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(ConvSection*);
		IterValue(List, AMTypeList, it)->valstrfunc = SectionPtr_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))SectionPtr_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(AMConvSectionList*);
		IterValue(List, AMTypeList, it)->valstrfunc = SectionList_valstrfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(ConvSectionType*);
		IterValue(List, AMTypeList, it)->valstrfunc = SectionTypePtr_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))SectionTypePtr_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(AMConvSectionTypeList*);
		IterValue(List, AMTypeList, it)->valstrfunc = SectionTypeList_valstrfunc;
		IterInc(List, AMTypeList, it);
		IterInc(List, AMTypeList, it);
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(States*);
		IterValue(List, AMTypeList, it)->valstrfunc = StatePtr_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))StatePtr_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(rnstream*);
		IterValue(List, AMTypeList, it)->valstrfunc = StreamPtr_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))StreamPtr_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(char*);
		IterValue(List, AMTypeList, it)->valstrfunc = String_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc = str2String;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(AMStringList*);
		IterValue(List, AMTypeList, it)->valstrfunc = StringList_valstrfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(System*);
		IterValue(List, AMTypeList, it)->valstrfunc = SystemPtr_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))SystemPtr_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(table*);
		IterValue(List, AMTypeList, it)->valstrfunc = TablePtr_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))TablePtr_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(ASITime);
		IterValue(List, AMTypeList, it)->valstrfunc = Time_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc = str2String;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(ConvTransfer*);
		IterValue(List, AMTypeList, it)->valstrfunc = TransferPtr_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))TransferPtr_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(TransferType*);
		IterValue(List, AMTypeList, it)->valstrfunc = TransferTypePtr_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))TransferTypePtr_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(vehicle*);
		IterValue(List, AMTypeList, it)->valstrfunc = VehiclePtr_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))VehiclePtr_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(AMVehicleList*);
		IterValue(List, AMTypeList, it)->valstrfunc = VehicleList_valstrfunc;
		IterInc(List, AMTypeList, it);
		IterInc(List, AMTypeList, it);
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(VehSeg*);
		IterValue(List, AMTypeList, it)->valstrfunc = VehSegPtr_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc  = (void (*)(char*))VehSegPtr_strvalfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(AMVehSegList*);
		IterValue(List, AMTypeList, it)->valstrfunc = VehSegList_valstrfunc;
		IterInc(List, AMTypeList, it);
		IterValue(List, AMTypeList, it)->size = sizeof(Velocity);
		IterValue(List, AMTypeList, it)->valstrfunc = Velocity_valstrfunc;
		IterValue(List, AMTypeList, it)->strvalfunc = str2String;
	}

}

